version: '3' #Versão do docker compose
services:
  app-php:
    container_name: php_81
    image: wyveo/nginx-php-fpm:php81
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: tail -f /dev/null