version: '3' #Versão do docker compose

services:
  app-python:
    container_name: python-infector
    image: googlesky/sqlmap:latest
    command: ["python", "sqlmap.py", "-hh"] #precisa decidir o comando